-- SQL Dialect: PostgreSQL (Sử dụng kiểu dữ liệu và cú pháp chuẩn hơn)
-- Ghi chú: Đã thay đổi DATETIME thành TIMESTAMP WITH TIME ZONE để có độ chính xác cao hơn về thời gian.
--          Đã thêm các hành động ON DELETE/ON UPDATE để quản lý tính toàn vẹn tham chiếu.
--          Đã thêm các ràng buộc UNIQUE để tránh dữ liệu trùng lặp.

-- BẢNG XÁC THỰC & HỒ SƠ NGƯỜI DÙNG
CREATE TABLE user_auth (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    email_verified BOOLEAN DEFAULT FALSE,
    role VARCHAR(20) DEFAULT 'user' CHECK (role IN ('user', 'admin', 'staff')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_user_auth_email ON user_auth(email);

CREATE TABLE user_profiles (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Quan hệ 1-1 với user_auth. Nếu user_auth bị xóa, hồ sơ cũng sẽ bị xóa theo.
    auth_id INT UNIQUE NOT NULL,
    last_name VARCHAR(255),
    first_name VARCHAR(255),
    phone VARCHAR(20),
    avatar_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (auth_id) REFERENCES user_auth(id) ON DELETE CASCADE
);

-- ĐỊA CHỈ NGƯỜI DÙNG
CREATE TABLE user_addresses (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL,
    full_name VARCHAR(255),
    phone VARCHAR(20),
    address_line TEXT,
    ward VARCHAR(100),
    district VARCHAR(100),
    city VARCHAR(100),
    postal_code VARCHAR(20),
    is_default BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    -- Nếu người dùng bị xóa, các địa chỉ của họ cũng sẽ bị xóa.
    FOREIGN KEY (user_id) REFERENCES user_auth(id) ON DELETE CASCADE
);

CREATE INDEX idx_user_address_user_id ON user_addresses(user_id);

-- DANH MỤC & SẢN PHẨM
CREATE TABLE categories (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) UNIQUE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE products (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    category_id INT,
    brand VARCHAR(100),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    -- Ngăn chặn việc xóa danh mục nếu vẫn còn sản phẩm thuộc danh mục đó.
    FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE RESTRICT
);

CREATE INDEX idx_products_category ON products(category_id);

-- THÔNG SỐ KỸ THUẬT (Định nghĩa cho mỗi danh mục)
CREATE TABLE product_specs (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id INT NOT NULL,
    name VARCHAR(100) NOT NULL,
    label VARCHAR(255),
    data_type VARCHAR(20) CHECK (data_type IN ('string', 'int', 'float', 'boolean')),
    required BOOLEAN DEFAULT FALSE,
    sort_order INT DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    -- Nếu danh mục bị xóa, các định nghĩa thông số của nó cũng bị xóa.
    FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE CASCADE,
    -- Đảm bảo tên thông số là duy nhất trong một danh mục.
    UNIQUE (category_id, name)
);

-- GIÁ TRỊ THÔNG SỐ KỸ THUẬT (Của từng sản phẩm)
CREATE TABLE product_spec_values (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id INT NOT NULL,
    spec_id INT NOT NULL,
    value_string VARCHAR(255),
    value_int INT,
    value_float DECIMAL(18, 4),
    value_boolean BOOLEAN,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    -- Nếu sản phẩm hoặc định nghĩa thông số bị xóa, giá trị này cũng sẽ bị xóa.
    FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE,
    FOREIGN KEY (spec_id) REFERENCES product_specs(id) ON DELETE CASCADE,
    -- Mỗi thông số chỉ có một giá trị cho mỗi sản phẩm.
    UNIQUE (product_id, spec_id)
);

-- BIẾN THỂ SẢN PHẨM (SKU)
CREATE TABLE product_variants (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id INT NOT NULL,
    sku VARCHAR(100) UNIQUE,
    stock INT NOT NULL CHECK (stock >= 0),
    price DECIMAL(12, 2) NOT NULL CHECK (price >= 0),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    -- Nếu sản phẩm bị xóa, các biến thể của nó cũng bị xóa.
    FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
);

CREATE INDEX idx_variants_product ON product_variants(product_id);

-- ĐƠN HÀNG & CHI TIẾT ĐƠN HÀNG
CREATE TABLE orders (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT, -- Có thể là NULL nếu muốn giữ lại đơn hàng của người dùng đã bị xóa.
    total_price DECIMAL(12, 2) NOT NULL,
    status VARCHAR(20) DEFAULT 'pending' CHECK (status IN ('pending', 'processing', 'shipped', 'delivered', 'cancelled', 'refunded')),
    
    -- Sao chép thông tin địa chỉ vào đơn hàng để đảm bảo tính lịch sử.
    -- Điều này quan trọng vì người dùng có thể thay đổi hoặc xóa địa chỉ của họ sau khi đặt hàng.
    shipping_full_name VARCHAR(255),
    shipping_phone VARCHAR(20),
    shipping_address_line TEXT,
    shipping_ward VARCHAR(100),
    shipping_district VARCHAR(100),
    shipping_city VARCHAR(100),
    shipping_postal_code VARCHAR(20),

    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    -- Nếu người dùng bị xóa, user_id trong đơn hàng sẽ được set thành NULL thay vì xóa cả đơn hàng.
    FOREIGN KEY (user_id) REFERENCES user_auth(id) ON DELETE SET NULL
);

CREATE INDEX idx_orders_user ON orders(user_id);

CREATE TABLE order_items (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id INT NOT NULL,
    product_variant_id INT, -- Có thể là NULL nếu sản phẩm bị xóa khỏi hệ thống.
    quantity INT NOT NULL CHECK (quantity > 0),
    -- Lưu lại giá tại thời điểm mua hàng.
    unit_price DECIMAL(12, 2) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    -- Nếu đơn hàng bị xóa, các mục trong đó cũng bị xóa.
    FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
    -- Ngăn việc xóa biến thể sản phẩm nếu nó đã từng được đặt hàng.
    FOREIGN KEY (product_variant_id) REFERENCES product_variants(id) ON DELETE SET NULL
);

CREATE INDEX idx_order_items_order ON order_items(order_id);

-- GIỎ HÀNG
CREATE TABLE shopping_carts (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Quan hệ 1-1, mỗi người dùng chỉ có một giỏ hàng.
    user_id INT UNIQUE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES user_auth(id) ON DELETE CASCADE
);

-- CÁC MỤC TRONG GIỎ HÀNG
CREATE TABLE cart_items (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cart_id INT NOT NULL,
    product_variant_id INT NOT NULL,
    quantity INT DEFAULT 1 CHECK (quantity > 0),
    is_selected BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    -- Nếu giỏ hàng hoặc biến thể sản phẩm bị xóa, mục này cũng bị xóa.
    FOREIGN KEY (cart_id) REFERENCES shopping_carts(id) ON DELETE CASCADE,
    FOREIGN KEY (product_variant_id) REFERENCES product_variants(id) ON DELETE CASCADE,
    -- Đảm bảo mỗi biến thể sản phẩm chỉ xuất hiện một lần trong một giỏ hàng.
    UNIQUE (cart_id, product_variant_id)
);
